// Generated by CoffeeScript 1.6.3
(function($) {
  var $map, $panel;
  $map = $("#scope_map");
  $panel = null;
  ($map.find(".scope-map-label")).on("click", function(e) {
    var $area, $box, area;
    $panel = ($(this)).next();
    $box = $panel.parent();
    area = (($box.attr("class")).match(/box-(\w+)/))[1];
    if (!$box.hasClass("on")) {
      $box.addClass("on");
      $area = $box.next();
      $.transit({
        to: $area
      });
      setTimeout(function() {
        ($(document)).one("click", function() {
          $.transit({
            from: $area
          });
          $box.removeClass("on");
        });
      });
    }
  });

  $map.find(".scope-map-panel").on('click','a',function(e){
    e.preventDefault();
  });



})($);
